### ISSUE TITLE
Transparent Navbar. Needs to be opaque with the defined css styling

### ISSUE THREAD

**Issue by thewashedcastle** [Agixury/Final_page#24]
Can dm me for more information

**Comment by sharananurag998** [comment]
I can work on this. Please send me the details.

**Comment by thewashedcastle** [comment]
The NAVBAR when scrolled down shows the background as it is transparent. I would like you to fix that one property keeping the old responsive behaviour of the navbar and the website as a whole.

I am assuming you know how to create a branch and pull and make changes accordingly. If not reply asap and ill walk you through the process.

Ill be putting your name up for the issue.

Regards

Calvin Dani

**Comment by sharananurag998** [comment]
Fixed the issue, please check the pull request.
